\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{}
    \pretitle{\vspace{\droptitle}}
  \posttitle{}
    \author{}
    \preauthor{}\postauthor{}
    \date{}
    \predate{}\postdate{}
  

\begin{document}

\section{Explore Red Wine Data by Huda
Rezq}\label{explore-red-wine-data-by-huda-rezq}

\section{Univariate Analysis}\label{univariate-analysis}

\begin{quote}
geting the data structure and then each attribute distribution.
\end{quote}

\begin{verbatim}
## [1] 1599   12
\end{verbatim}

\begin{verbatim}
## 'data.frame':    1599 obs. of  12 variables:
##  $ fixed.acidity       : num  7.4 7.8 7.8 11.2 7.4 7.4 7.9 7.3 7.8 7.5 ...
##  $ volatile.acidity    : num  0.7 0.88 0.76 0.28 0.7 0.66 0.6 0.65 0.58 0.5 ...
##  $ citric.acid         : num  0 0 0.04 0.56 0 0 0.06 0 0.02 0.36 ...
##  $ residual.sugar      : num  1.9 2.6 2.3 1.9 1.9 1.8 1.6 1.2 2 6.1 ...
##  $ chlorides           : num  0.076 0.098 0.092 0.075 0.076 0.075 0.069 0.065 0.073 0.071 ...
##  $ free.sulfur.dioxide : num  11 25 15 17 11 13 15 15 9 17 ...
##  $ total.sulfur.dioxide: num  34 67 54 60 34 40 59 21 18 102 ...
##  $ density             : num  0.998 0.997 0.997 0.998 0.998 ...
##  $ pH                  : num  3.51 3.2 3.26 3.16 3.51 3.51 3.3 3.39 3.36 3.35 ...
##  $ sulphates           : num  0.56 0.68 0.65 0.58 0.56 0.56 0.46 0.47 0.57 0.8 ...
##  $ alcohol             : num  9.4 9.8 9.8 9.8 9.4 9.4 9.4 10 9.5 10.5 ...
##  $ quality             : int  5 5 5 6 5 5 5 7 7 5 ...
\end{verbatim}

\begin{verbatim}
##  fixed.acidity   volatile.acidity  citric.acid    residual.sugar  
##  Min.   : 4.60   Min.   :0.1200   Min.   :0.000   Min.   : 0.900  
##  1st Qu.: 7.10   1st Qu.:0.3900   1st Qu.:0.090   1st Qu.: 1.900  
##  Median : 7.90   Median :0.5200   Median :0.260   Median : 2.200  
##  Mean   : 8.32   Mean   :0.5278   Mean   :0.271   Mean   : 2.539  
##  3rd Qu.: 9.20   3rd Qu.:0.6400   3rd Qu.:0.420   3rd Qu.: 2.600  
##  Max.   :15.90   Max.   :1.5800   Max.   :1.000   Max.   :15.500  
##    chlorides       free.sulfur.dioxide total.sulfur.dioxide
##  Min.   :0.01200   Min.   : 1.00       Min.   :  6.00      
##  1st Qu.:0.07000   1st Qu.: 7.00       1st Qu.: 22.00      
##  Median :0.07900   Median :14.00       Median : 38.00      
##  Mean   :0.08747   Mean   :15.87       Mean   : 46.47      
##  3rd Qu.:0.09000   3rd Qu.:21.00       3rd Qu.: 62.00      
##  Max.   :0.61100   Max.   :72.00       Max.   :289.00      
##     density             pH          sulphates         alcohol     
##  Min.   :0.9901   Min.   :2.740   Min.   :0.3300   Min.   : 8.40  
##  1st Qu.:0.9956   1st Qu.:3.210   1st Qu.:0.5500   1st Qu.: 9.50  
##  Median :0.9968   Median :3.310   Median :0.6200   Median :10.20  
##  Mean   :0.9967   Mean   :3.311   Mean   :0.6581   Mean   :10.42  
##  3rd Qu.:0.9978   3rd Qu.:3.400   3rd Qu.:0.7300   3rd Qu.:11.10  
##  Max.   :1.0037   Max.   :4.010   Max.   :2.0000   Max.   :14.90  
##     quality     
##  Min.   :3.000  
##  1st Qu.:5.000  
##  Median :6.000  
##  Mean   :5.636  
##  3rd Qu.:6.000  
##  Max.   :8.000
\end{verbatim}

\begin{quote}
The red wine dataset contains 1,599 observations with 13 variables.
\end{quote}

\section{Univariate Plots Section}\label{univariate-plots-section}

\subsection{Quality}\label{quality}

\includegraphics{projecttemplate_files/figure-latex/unnamed-chunk-2-1.pdf}

It seems that overall the wine dataset is normally distributed with an
average of approximately 6, this is an indication that it's a collection
of fairly good-quality wines, where 0 (very bad) and 10 (very
excellent). I chose to use geom bars to represent wine quaility data
because quality is a discrete value.

\subsection{Fixed Acidity}\label{fixed-acidity}

Most acids involved with wine are fixed or nonvolatile (do not evaporate
readily).
\includegraphics{projecttemplate_files/figure-latex/unnamed-chunk-3-1.pdf}
\includegraphics{projecttemplate_files/figure-latex/unnamed-chunk-3-2.pdf}

Fixed acidity values range between 4 and 16, with most values range
between 7 and 9. The distribution is slightly positively skewed.
Transforming the x-axis into log scale can make it more normally
distributed.

\subsection{Volatile Acidity}\label{volatile-acidity}

\includegraphics{projecttemplate_files/figure-latex/unnamed-chunk-4-1.pdf}
\includegraphics{projecttemplate_files/figure-latex/unnamed-chunk-4-2.pdf}

Fixed acidity and volatile acidity appear to be long tailed as well, and
transforming their log appears to make them closer to a normal
distribution. Of course, since pH is a logarithmic term, and is normal
in our data set, then it would be sense for the log of acidity levels to
also be approximately normal. Variances are confirmed to be a relevant
decrease for fixed acidity but not entirely relevant for volatile
acidity.

\subsection{Citric Acid}\label{citric-acid}

\includegraphics{projecttemplate_files/figure-latex/unnamed-chunk-5-1.pdf}

\begin{verbatim}
## [1] 132
\end{verbatim}

Most red wines are of a citric acid, which adds `freshness' and flavor
to wines, between {[}0.1 - 0.5{]} g/dm\^{}3: mean is about 0.27
g/dm\^{}3 and median is about 0.26 g/dm\^{}3, which is reasonable as
citric acid is usually found in small quantities.

\subsection{Residual Sugar}\label{residual-sugar}

\includegraphics{projecttemplate_files/figure-latex/unnamed-chunk-7-1.pdf}
\includegraphics{projecttemplate_files/figure-latex/unnamed-chunk-7-2.pdf}

Most residual sugar values range between 1.5 and 2.5. There are a few
outliers with large values. When zoom in and look at values below 5, the
distribution appears normal.

\subsection{Chlorides}\label{chlorides}

\includegraphics{projecttemplate_files/figure-latex/unnamed-chunk-8-1.pdf}
\includegraphics{projecttemplate_files/figure-latex/unnamed-chunk-8-2.pdf}

Most chlorides values range between 0.05 to 0.1. The histogram is
positively skewed. There are a few outliers with large values. When zoom
in and look at values below 0.2, the distribution appears normal.

\subsection{Free Sulfur Dioxide}\label{free-sulfur-dioxide}

\includegraphics{projecttemplate_files/figure-latex/unnamed-chunk-9-1.pdf}

The distribution of free sulfur dioxide is highly positively skewed.

\subsection{Total Sulfur Dioxide}\label{total-sulfur-dioxide}

\includegraphics{projecttemplate_files/figure-latex/unnamed-chunk-10-1.pdf}
\includegraphics{projecttemplate_files/figure-latex/unnamed-chunk-10-2.pdf}

The distribution of total sulfur dioxide is higly positively skewed. And
there are a few outliers with very large values. Transforming the x-axis
into log scale can make it more normally distributed.

\subsection{Density}\label{density}

\includegraphics{projecttemplate_files/figure-latex/unnamed-chunk-11-1.pdf}

Density values range between 0.990 and 1.004 with most values range from
0.995 and 0.998. The distribution of density values are symmetrical
centered around 0.9965.

\subsection{pH}\label{ph}

\includegraphics{projecttemplate_files/figure-latex/unnamed-chunk-12-1.pdf}

Most pH values range between 3.15 and 3.45. The distribution of pH is
symmetrical centered around 3.3.

\subsection{Sulphates}\label{sulphates}

\includegraphics{projecttemplate_files/figure-latex/unnamed-chunk-13-1.pdf}
\includegraphics{projecttemplate_files/figure-latex/unnamed-chunk-13-2.pdf}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.3300  0.5500  0.6200  0.6581  0.7300  2.0000
\end{verbatim}

Most sulphates values range between 0.5 and 0.75. The distribution is
positively skewed. There are a few ourliers with large sulphates values.
Transforming the x-axis into log scale can make it more normally
distributed.

\subsection{Alcohol}\label{alcohol}

\includegraphics{projecttemplate_files/figure-latex/unnamed-chunk-14-1.pdf}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    8.40    9.50   10.20   10.42   11.10   14.90
\end{verbatim}

The alcohol values range between 8.5 and 15. mean and median are about
10\%. The distribution of alcohol value is positively skewed.

\subsubsection{What is the structure of your
dataset?}\label{what-is-the-structure-of-your-dataset}

There are 11 attributes in the dataset + output (quality rating) between
0 = very bad and 10 = very excellent where at least 3 wine experts rated
the quality. Each row corresponds to one particular wine with total 1599
different red wines in the data set. \#\#\# What is/are the main
feature(s) of interest in your dataset? The main feature of interest is
the output attribute quality. I am trying to figure out which of the 11
input attribute contribute to a high quality value. \#\#\# What other
features in the dataset do you think will help support your
investigation into your feature(s) of interest? alcohol, volatile
acidity, sulphates, and maybe density. \#\#\# Did you create any new
variables from existing variables in the dataset? No. \#\#\# Of the
features you investigated, were there any unusual distributions?Did you
perform any operations on the data to tidy, adjust, or change the form
of the data? If so, why did you do this?

The possible quality values are from 0 to 10, but our data set only has
quality values from 3 to 8, which means there are no extremely bad red
wines or extrememly good wines in out data set. The vast majority of red
wines in the data set has a quality value either 5 or 6, with very fewer
wines with quality values 3, 4, 7 or 8, which makes the data set
unbalanced.

\section{Bivariate Plots Section}\label{bivariate-plots-section}

\includegraphics{projecttemplate_files/figure-latex/Correlation_Matrix-1.pdf}

I chose to show mainly the chemical features that perhaps has a
meaningful correlation with wine quality. from the above correlation
matrix, quality correlates positivly with alcohol, with a correlation
coefficient of about 0.48. On the other hand, it correlates negatively
with volatile acid, with a -0.39 coefficient. Citric and volatile acids
tend to correlate negatively.

\begin{verbatim}
##                      fixed.acidity volatile.acidity citric.acid
## fixed.acidity           1.00000000     -0.256130895  0.67170343
## volatile.acidity       -0.25613089      1.000000000 -0.55249568
## citric.acid             0.67170343     -0.552495685  1.00000000
## residual.sugar          0.11477672      0.001917882  0.14357716
## chlorides               0.09370519      0.061297772  0.20382291
## free.sulfur.dioxide    -0.15379419     -0.010503827 -0.06097813
## total.sulfur.dioxide   -0.11318144      0.076470005  0.03553302
## density                 0.66804729      0.022026232  0.36494718
## pH                     -0.68297819      0.234937294 -0.54190414
## sulphates               0.18300566     -0.260986685  0.31277004
## alcohol                -0.06166827     -0.202288027  0.10990325
##                      residual.sugar    chlorides free.sulfur.dioxide
## fixed.acidity           0.114776724  0.093705186        -0.153794193
## volatile.acidity        0.001917882  0.061297772        -0.010503827
## citric.acid             0.143577162  0.203822914        -0.060978129
## residual.sugar          1.000000000  0.055609535         0.187048995
## chlorides               0.055609535  1.000000000         0.005562147
## free.sulfur.dioxide     0.187048995  0.005562147         1.000000000
## total.sulfur.dioxide    0.203027882  0.047400468         0.667666450
## density                 0.355283371  0.200632327        -0.021945831
## pH                     -0.085652422 -0.265026131         0.070377499
## sulphates               0.005527121  0.371260481         0.051657572
## alcohol                 0.042075437 -0.221140545        -0.069408354
##                      total.sulfur.dioxide     density          pH
## fixed.acidity                 -0.11318144  0.66804729 -0.68297819
## volatile.acidity               0.07647000  0.02202623  0.23493729
## citric.acid                    0.03553302  0.36494718 -0.54190414
## residual.sugar                 0.20302788  0.35528337 -0.08565242
## chlorides                      0.04740047  0.20063233 -0.26502613
## free.sulfur.dioxide            0.66766645 -0.02194583  0.07037750
## total.sulfur.dioxide           1.00000000  0.07126948 -0.06649456
## density                        0.07126948  1.00000000 -0.34169933
## pH                            -0.06649456 -0.34169933  1.00000000
## sulphates                      0.04294684  0.14850641 -0.19664760
## alcohol                       -0.20565394 -0.49617977  0.20563251
##                         sulphates     alcohol
## fixed.acidity         0.183005664 -0.06166827
## volatile.acidity     -0.260986685 -0.20228803
## citric.acid           0.312770044  0.10990325
## residual.sugar        0.005527121  0.04207544
## chlorides             0.371260481 -0.22114054
## free.sulfur.dioxide   0.051657572 -0.06940835
## total.sulfur.dioxide  0.042946836 -0.20565394
## density               0.148506412 -0.49617977
## pH                   -0.196647602  0.20563251
## sulphates             1.000000000  0.09359475
## alcohol               0.093594750  1.00000000
\end{verbatim}

Quality correlates highly with alcohol and volatile acidity (correlation
coefficient \textgreater{} 0.3), but also there seems to be interesting
correlations with some of the supporting variables. Free sulfur dioxide
correlates highly with total sulfur dixoide, fixed acidity with both pH
and density, density with both alcohol and residual sugar, sulphates and
chlorides. Let me generate a correlation matrix to have a better
insight.

\subsection{Quality vs Fixed Acidity}\label{quality-vs-fixed-acidity}

\includegraphics{projecttemplate_files/figure-latex/unnamed-chunk-16-1.pdf}

There isn't a clear trend between fixed acidity and quality.

\subsection{Quality vs Volatile
Acidity}\label{quality-vs-volatile-acidity}

\includegraphics{projecttemplate_files/figure-latex/unnamed-chunk-17-1.pdf}

The higher the quality, the lower the volatile acidity.

\subsection{Quality vs Citric Acid}\label{quality-vs-citric-acid}

\includegraphics{projecttemplate_files/figure-latex/unnamed-chunk-18-1.pdf}

The higher the quality, the higher the citric acid.

\subsection{Quality vs Residual Sugar}\label{quality-vs-residual-sugar}

\includegraphics{projecttemplate_files/figure-latex/unnamed-chunk-19-1.pdf}

There isn't a clear trend between residual sugar and quality.

\subsection{Quality vs Chlorides}\label{quality-vs-chlorides}

\includegraphics{projecttemplate_files/figure-latex/unnamed-chunk-20-1.pdf}
\includegraphics{projecttemplate_files/figure-latex/unnamed-chunk-20-2.pdf}

After zoom in, one can see the higher the quality, the lower the
chlorides.

\subsection{Quality vs Free Sulfur
Dioxide}\label{quality-vs-free-sulfur-dioxide}

\includegraphics{projecttemplate_files/figure-latex/unnamed-chunk-21-1.pdf}

There isn't a clear trend between free sulfur dioxide and quality.

\subsection{Quality vs Total Sulfur
Dioxide}\label{quality-vs-total-sulfur-dioxide}

\includegraphics{projecttemplate_files/figure-latex/unnamed-chunk-22-1.pdf}

There isn't a clear trend between total sulfur dioxide and quality.

\subsection{Quality vs Density}\label{quality-vs-density}

\includegraphics{projecttemplate_files/figure-latex/unnamed-chunk-23-1.pdf}

The higher the quality, the lower the density.

\subsection{Quality vs pH}\label{quality-vs-ph}

\includegraphics{projecttemplate_files/figure-latex/unnamed-chunk-24-1.pdf}

The higher the quality, the lower the pH.

\subsection{Quality vs Sulphates}\label{quality-vs-sulphates}

\includegraphics{projecttemplate_files/figure-latex/unnamed-chunk-25-1.pdf}

The higher the quality, the higher the sulphates.

\subsection{Quality vs Alcohol}\label{quality-vs-alcohol}

\includegraphics{projecttemplate_files/figure-latex/unnamed-chunk-26-1.pdf}

The higher the quality, the higher the alcohol.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ citric.acid,}\DataTypeTok{y =}\NormalTok{ sulphates), }\DataTypeTok{data =}\NormalTok{ rw) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_point}\NormalTok{(}\DataTypeTok{alpha =} \DecValTok{1}\OperatorTok{/}\DecValTok{5}\NormalTok{, }\DataTypeTok{position =} \KeywordTok{position_jitter}\NormalTok{(}\DataTypeTok{h =} \DecValTok{0}\NormalTok{), }\DataTypeTok{color =} \StringTok{'#993366'}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_smooth}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using method = 'gam' and formula 'y ~ s(x, bs = "cs")'
\end{verbatim}

\includegraphics{projecttemplate_files/figure-latex/Bivariate_Plots_Sulph_and_Citric-1.pdf}

As citric acid level increases, sulphates level tend to increase as
well.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ volatile.acidity, }\DataTypeTok{y =}\NormalTok{ citric.acid), }\DataTypeTok{data =}\NormalTok{ rw) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_point}\NormalTok{(}\DataTypeTok{alpha=}\DecValTok{1}\OperatorTok{/}\DecValTok{5}\NormalTok{, }\DataTypeTok{color =} \StringTok{'#993366'}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_smooth}\NormalTok{(}\DataTypeTok{se =} \OtherTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using method = 'gam' and formula 'y ~ s(x, bs = "cs")'
\end{verbatim}

\includegraphics{projecttemplate_files/figure-latex/Bivariate_Plots_Cit_and_Vol-1.pdf}

There's an interesting negative correlation between citric and volatile
acid that can be clearly shown using geom\_smooth function.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ density, }\DataTypeTok{y =}\NormalTok{ residual.sugar), }\DataTypeTok{data =}\NormalTok{ rw) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_point}\NormalTok{(}\DataTypeTok{alpha =} \DecValTok{1}\OperatorTok{/}\DecValTok{5}\NormalTok{, }\DataTypeTok{color =} \StringTok{'#993366'}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_smooth}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using method = 'gam' and formula 'y ~ s(x, bs = "cs")'
\end{verbatim}

\includegraphics{projecttemplate_files/figure-latex/Bivariate_Plots_Sug_and_Den-1.pdf}

As density increases, residual sugar amount increases as well.
Geom\_smooth helped in showing the positive correlation.

\section{Bivariate Analysis}\label{bivariate-analysis}

\begin{quote}
\textbf{Tip}: As before, summarize what you found in your bivariate
explorations here. Use the questions below to guide your discussion.
\end{quote}

\subsubsection{Talk about some of the relationships you observed in this
part of the investigation. How did the feature(s) of interest vary with
other features in the
dataset?}\label{talk-about-some-of-the-relationships-you-observed-in-this-part-of-the-investigation.-how-did-the-features-of-interest-vary-with-other-features-in-the-dataset}

There are a few attributes exhibit some trends that look promising to be
used to predict quality.

\begin{itemize}
\tightlist
\item
  Quality is positively correlated with citric acid, sulphates, and
  alcohol.
\item
  Quality increases is negatively correlated with volatile acidity,
  chlorides, density, and pH.
\end{itemize}

\subsubsection{Did you observe any interesting relationships between the
other features (not the main feature(s) of
interest)?}\label{did-you-observe-any-interesting-relationships-between-the-other-features-not-the-main-features-of-interest}

Fixed acidity and citric acid are positively correlated because the
fixed acidity includes citric acid. * Total sulfur dioxide and free
sulfur dioxide are positively correlated because total sulfur dioxide
includes free sulfur dioxide. * Fixed acidity and pH are negatively
correlated because higher concentration of fixed acidity makes the wine
more acidic, therefore the wine has a lower pH. * Citric acid and pH are
negatively correlated because higher concentration of citric acid, which
is non-volatile, makes the wine more acidic, therefore the wine has a
lower pH. * Density and alcohol are negatively correlated because
alcohol has a lower density than water, therefore wines that contain
more alcohol have a lower density. * Density and fixed acidity are
positively correlated because the main fixed acids in wine, tartaric
acid, has a higher density than water, therefore wines that contain more
tartaric acid have a higher density.

\subsubsection{What was the strongest relationship you
found?}\label{what-was-the-strongest-relationship-you-found}

The quality of the wine is positivley and highly correlated with
alcohol. Moreover, alcohol correlates very highly with the pH levels of
the wine. On the other hand, the citric acid levels of the wine
correlates highly and negatively with volatile acidity levels which in
return correlates with wine quality as well.

\section{Multivariate Plots Section}\label{multivariate-plots-section}

\includegraphics{projecttemplate_files/figure-latex/unnamed-chunk-27-1.pdf}

It looks like the higher quality red wines tend to be concentrated in
the top left of the plot. This tends to be where the higher alcohol
content (larger dots) are concentrated as well.

Let's try summarizing quality using a contour plot of alcohol and
sulphate content:
\includegraphics{projecttemplate_files/figure-latex/unnamed-chunk-28-1.pdf}
This shows that higher quality red wines are generally located near the
upper right of the scatter plot (darker contour lines) wheras lower
quality red wines are generally located in the bottom right.

Let's make a similar plot but this time quality will be visualized using
density plots along the x and y axis and color :

\includegraphics{projecttemplate_files/figure-latex/unnamed-chunk-29-1.pdf}

Again, this clearly illustrates that higher quality wines are found near
the top right of the plot.

\subsubsection{Talk about some of the relationships you observed in this
part of the investigation. Were there features that strengthened each
other in terms of looking at your feature(s) of
interest?}\label{talk-about-some-of-the-relationships-you-observed-in-this-part-of-the-investigation.-were-there-features-that-strengthened-each-other-in-terms-of-looking-at-your-features-of-interest}

By combining the most promising attribute from bivariate section,
volatile acidity, with one of the other attributes (citric acid,
sulphates, alcohol, chlorides, density and pH), one can further separate
high quality wines and low quality wines.

\subsubsection{Were there any interesting or surprising interactions
between
features?}\label{were-there-any-interesting-or-surprising-interactions-between-features}

By looking at density vs fixed acidity and alcohol, one can see that
fixed acidity has a larger impact on the density of the wine than
alcohol.

\subsubsection{\texorpdfstring{OPTIONAL: Did you create any models with
your dataset? Discuss the\\
strengths and limitations of your
model.}{OPTIONAL: Did you create any models with your dataset? Discuss the strengths and limitations of your model.}}\label{optional-did-you-create-any-models-with-your-dataset-discuss-the-strengths-and-limitations-of-your-model.}

\begin{center}\rule{0.5\linewidth}{\linethickness}\end{center}

\section{Final Plots and Summary}\label{final-plots-and-summary}

\subsection{Plot I}\label{plot-i}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ quality), }\DataTypeTok{data =}\NormalTok{ rw) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{y =}\NormalTok{ (..count..)}\OperatorTok{/}\KeywordTok{sum}\NormalTok{(..count..))) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_text}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{y =}\NormalTok{ ((..count..)}\OperatorTok{/}\KeywordTok{sum}\NormalTok{(..count..)), }
            \DataTypeTok{label =}\NormalTok{ scales}\OperatorTok{::}\KeywordTok{percent}\NormalTok{((..count..)}\OperatorTok{/}\KeywordTok{sum}\NormalTok{(..count..))), }
            \DataTypeTok{stat =} \StringTok{"count"}\NormalTok{, }
            \DataTypeTok{vjust =} \OperatorTok{-}\FloatTok{0.25}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{scale_y_continuous}\NormalTok{(}\DataTypeTok{labels =}\NormalTok{ scales}\OperatorTok{::}\NormalTok{percent) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\StringTok{'Quality'}\NormalTok{) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{ylab}\NormalTok{(}\StringTok{'Percent'}\NormalTok{) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{'Quality Relative Frequency Histogram'}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{panel.grid.major =} \KeywordTok{element_blank}\NormalTok{(), }
        \DataTypeTok{panel.grid.minor =} \KeywordTok{element_blank}\NormalTok{(),}
        \DataTypeTok{panel.background =} \KeywordTok{element_blank}\NormalTok{())}
\end{Highlighting}
\end{Shaded}

\includegraphics{projecttemplate_files/figure-latex/unnamed-chunk-30-1.pdf}

The possible quality values are ranging from 0 to 10, however, all red
wines in the dataset have quality values between 3 and 8. There is no
any really bad wine with quality below 3 or any really good wine with
quality above 8. Also, most of the red wines have quality 5 or 6, which
make the dataset not well balanced.

The strongest correlation coefficient was found between alcohol and
quality. Now let's look at the alcohol content by red wine quality using
a density plot function:
\includegraphics{projecttemplate_files/figure-latex/unnamed-chunk-31-1.pdf}

Clearly we see that the density plots for higher quality red wines (as
indicated by the red plots) are right shifted, meaning they have a
comparatively high alcohol content, compared to the lower quality red
wines. However, the main anomoly to this trend appears to be red wines
having a quality ranking of 5.

Here are the summary statistics for alcohol content at each quality
level:

\begin{verbatim}
## rw$quality: 3
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   8.400   9.725   9.925   9.955  10.575  11.000 
## -------------------------------------------------------- 
## rw$quality: 4
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    9.00    9.60   10.00   10.27   11.00   13.10 
## -------------------------------------------------------- 
## rw$quality: 5
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##     8.5     9.4     9.7     9.9    10.2    14.9 
## -------------------------------------------------------- 
## rw$quality: 6
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    8.40    9.80   10.50   10.63   11.30   14.00 
## -------------------------------------------------------- 
## rw$quality: 7
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    9.20   10.80   11.50   11.47   12.10   14.00 
## -------------------------------------------------------- 
## rw$quality: 8
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    9.80   11.32   12.15   12.09   12.88   14.00
\end{verbatim}

Sulphates were found to also found to be correlated with red wine
quality (R\^{}2= 0.25) while volatile acid had a negative correlation
(R\^{}2=-0.39). We can visualize the relationships betwen these two
variables, along with alcohol content and red wine quality using a
scatter plot:
\includegraphics{projecttemplate_files/figure-latex/unnamed-chunk-33-1.pdf}

We see a clear trend where higher quality red wines (red dots), are
concentrated in the upper right of the figure, while their also tends to
be larger dots concentrated in this area.

And here is a summary of red wine alcohol content by quality rating:

\begin{verbatim}
## rw$quality: 3
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   8.400   9.725   9.925   9.955  10.575  11.000 
## -------------------------------------------------------- 
## rw$quality: 4
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    9.00    9.60   10.00   10.27   11.00   13.10 
## -------------------------------------------------------- 
## rw$quality: 5
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##     8.5     9.4     9.7     9.9    10.2    14.9 
## -------------------------------------------------------- 
## rw$quality: 6
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    8.40    9.80   10.50   10.63   11.30   14.00 
## -------------------------------------------------------- 
## rw$quality: 7
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    9.20   10.80   11.50   11.47   12.10   14.00 
## -------------------------------------------------------- 
## rw$quality: 8
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    9.80   11.32   12.15   12.09   12.88   14.00
\end{verbatim}

By sulphate content:

\begin{verbatim}
## rw$quality: 3
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.4000  0.5125  0.5450  0.5700  0.6150  0.8600 
## -------------------------------------------------------- 
## rw$quality: 4
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.3300  0.4900  0.5600  0.5964  0.6000  2.0000 
## -------------------------------------------------------- 
## rw$quality: 5
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   0.370   0.530   0.580   0.621   0.660   1.980 
## -------------------------------------------------------- 
## rw$quality: 6
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.4000  0.5800  0.6400  0.6753  0.7500  1.9500 
## -------------------------------------------------------- 
## rw$quality: 7
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.3900  0.6500  0.7400  0.7413  0.8300  1.3600 
## -------------------------------------------------------- 
## rw$quality: 8
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.6300  0.6900  0.7400  0.7678  0.8200  1.1000
\end{verbatim}

And by volatile.acidity

\begin{verbatim}
## rw$quality: 3
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.4400  0.6475  0.8450  0.8845  1.0100  1.5800 
## -------------------------------------------------------- 
## rw$quality: 4
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   0.230   0.530   0.670   0.694   0.870   1.130 
## -------------------------------------------------------- 
## rw$quality: 5
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   0.180   0.460   0.580   0.577   0.670   1.330 
## -------------------------------------------------------- 
## rw$quality: 6
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.1600  0.3800  0.4900  0.4975  0.6000  1.0400 
## -------------------------------------------------------- 
## rw$quality: 7
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.1200  0.3000  0.3700  0.4039  0.4850  0.9150 
## -------------------------------------------------------- 
## rw$quality: 8
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.2600  0.3350  0.3700  0.4233  0.4725  0.8500
\end{verbatim}

\section{Reflection}\label{reflection}

The above analysis considered the relationship of a number of red wine
attributes with the quality rankings of different wines. Melting the
dataframe and using facet grids was really helpful for visualizing the
distribution of each of the parameters with the use of boxplots and
histograms. Most of the parameters were found to be normally distributed
while citirc acid, free sulfur dioxide and total sulfur dioxide and
alcohol had more of a lognormal distribution.

Using the insights from correlation coefficients provided by the paired
plots, it was interesting exploring quality using density plots with a
different color for each quality. Once I had this plotted it was
interesting to build up the multivariate scatter plots to visualize the
relationship of different variables with quality by also varying the
point size, using density plots on the x and y axis, and also using
density plots.

A next step would be to develop a statistical model to predict red wine
quality based on the data in this dataset.


\end{document}
